# Generated by Django 5.2.12 on 2026-03-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='firebase_uid',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
