# Generated by Django 5.2.12 on 2026-03-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_interviewsession_firebase_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='firebase_uid',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
